test all failure

diff --git a/.azure-pipelines/run-test-elastictest-template.yml b/.azure-pipelines/run-test-elastictest-template.yml
--- a/.azure-pipelines/run-test-elastictest-template.yml
+++ b/.azure-pipelines/run-test-elastictest-template.yml
@@ -233,7 +233,6 @@ steps:
       echo -e "\033[33mSONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com \033[0m"
       IFS=',' read -ra TEST_PLAN_ID_LIST <<< "$TEST_PLAN_ID_LIST_STRING"
       failure_count=0
-      echo "test plan num: ${#TEST_PLAN_ID_LIST[@]}"
       for TEST_PLAN_ID in "${TEST_PLAN_ID_LIST[@]}"
       do
           echo -e -n "\033[33mPlease visit Elastictest page \033[0m"
@@ -241,9 +240,10 @@ steps:
           echo -e "\033[33mfor detailed test plan progress \033[0m"
           # When "LOCK_TESTBED" finish, it changes into "PREPARE_TESTBED"
           echo "[test_plan.py] poll LOCK_TESTBED status"
-          python ./.azure-pipelines/test_plan.py poll -i $TEST_PLAN_ID --expected-state LOCK_TESTBED || ((failure_count++))
+          python ./.azure-pipelines/test_plan.py poll -i $TEST_PLAN_ID --expected-state LOCK_TESTBED --add-a-test-code test || ((failure_count++))
       done
 
+      echo "$failure_count test plan fails"
       if [ $failure_count -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
           exit 3
       fi
